# Dagster libraries to run both dagster-webserver and the dagster-daemon. Does not
# need to have access to any pipeline code.

FROM python:3.10-slim

RUN pip install \
    dagster \
    dagster-graphql \
    dbt-core==1.8.4 \
    dbt-bigquery==1.8.3 \
    dagster-webserver \
    dagster-postgres \
    dagster-docker


RUN pip install --upgrade dbt-bigquery==1.8.3
# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME
COPY dbt-437212-d8b5c64d8b36.json $DAGSTER_HOME

WORKDIR $DAGSTER_HOME