FROM python:3.10-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagster-webserver and dagster-daemon, and to load the DagsterInstance

RUN pip install --upgrade pip && \
    pip install \
    dagster \
    dbt-core==1.8.4 \
    dbt-bigquery==1.8.3 \
    dagster-postgres \
    dagster-docker

    
RUN pip install --upgrade dbt-bigquery==1.8.3

# Add repository code

WORKDIR /opt/dagster/app

COPY repo.py /opt/dagster/app
COPY dbt-437212-d8b5c64d8b36.json /opt/dagster/app
# Run dagster gRPC server on port 4000

EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "repo.py"]